Repository Treblle/treblle-laravel, pull requests merged in 2022-01, with the labels that each got.

#6 5-two-api-responses-registered-when-using-laravel-octane
  src/Middlewares/TreblleMiddleware.php
Labels: bug

#14 feat: added test cases and removed laravel 6 support
  .github/workflows/php-unit.yml
  .gitignore
  .php-cs-fixer.dist
  composer.json
  phpunit.xml.dist
  src/Clients/HasFake.php
  src/Clients/TreblleClient.php
  src/Commands/SetupCommand.php
  tests/Clients/TreblleClientTest.php
  tests/Commands/SetUpCommandTest.php
  tests/TestCase.php
Labels: enhancement

#16 10-adding-a-editorconfig-file
  .editorconfig
  README.md
Labels: enhancement

#17 9-adding-a-changelog
  CHANGELOG.md
Labels: documentation

#18 8-provide-complete-control-on-mask-fields
  README.md
  config/treblle.php
  src/Middlewares/TreblleMiddleware.php
Labels: enhancement

#19 12-add-issues-templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#20 fix: fixes issue #7 and typo in readme
  .github/workflows/php-cs-fixer.yml
  README.md
Labels: bug
